carbonrelay:
  image: os/carbon
  command: relay
  restart: always
  ports:
   - "2003:2003"
   - "2004:2004"
  volumes:
   - ./carbon/relay:/etc/carbon
  volumes_from:
   - monitoring_whisper_1
  links:
   - carboncache1
   - carboncache2

carboncache1:
  image: os/carbon
  command: cache
  restart: always
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./carbon/cache:/etc/carbon

carboncache2:
  image: os/carbon
  command: cache
  restart: always
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./carbon/cache:/etc/carbon

graphite:
  image: os/graphite_web
  command: graphiteweb
  restart: always
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./graphite_web:/etc/graphite
  links:
   - carboncache1
   - carboncache2

grafana:
  image: os/grafana
  restart: always
  links:
   - graphite
  volumes:
   - ./grafana/grafana.ini:/etc/grafana/grafana.ini

nginx:
  image: nginx:1.9.5
  restart: always
  ports:
   - "443:443"
  volumes:
   - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
   - ./nginx/ssl:/etc/nginx/ssl
  links:
   - graphite
   - grafana

