carbonrelay:
  image: os/carbon
  command: relay
  restart: always
  ports:
   - "2003:2003"
   - "2004:2004"
  volumes:
   - ./carbon/relay:/etc/carbon
  volumes_from:
   - monitoring_whisper_1
  links:
   - carboncache1
   - carboncache2

carboncache1:
  image: os/carbon
  command: cache
  restart: always
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./carbon/cache:/etc/carbon

carboncache2:
  image: os/carbon
  command: cache
  restart: always
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./carbon/cache:/etc/carbon

graphite:
  image: os/graphite_web
  command: graphiteweb
  restart: always
  ports:
   - "80:80"
  volumes_from:
   - monitoring_whisper_1
  volumes:
   - ./graphite_web:/etc/graphite
  links:
   - carboncache1
   - carboncache2

grafana:
  image: os/grafana
  restart: always
  ports:
   - "81:3000"
  links:
   - graphite

